var tree = [["Elastification",,"",
                [["Client","Elastification\/Client.html","",
                [["Exception","Elastification\/Client\/Exception.html","",
                [["ClientException","Elastification\/Client\/Exception\/ClientException.html"," < Exception",
                [        ]],["RequestException","Elastification\/Client\/Exception\/RequestException.html"," < Exception",
                [        ]],["RequestManagerException","Elastification\/Client\/Exception\/RequestManagerException.html"," < Exception",
                [        ]],["ResponseException","Elastification\/Client\/Exception\/ResponseException.html"," < Exception",
                [        ]]        ]],["Request","Elastification\/Client\/Request.html","",
                [["Shared","Elastification\/Client\/Request\/Shared.html","",
                [["AbstractBaseRequest","Elastification\/Client\/Request\/Shared\/AbstractBaseRequest.html","",
                [        ]],["AbstractCreateDocumentRequest","Elastification\/Client\/Request\/Shared\/AbstractCreateDocumentRequest.html"," < AbstractBaseRequest",
                [        ]],["AbstractDeleteDocumentRequest","Elastification\/Client\/Request\/Shared\/AbstractDeleteDocumentRequest.html"," < AbstractBaseRequest",
                [        ]],["AbstractGetDocumentRequest","Elastification\/Client\/Request\/Shared\/AbstractGetDocumentRequest.html"," < AbstractBaseRequest",
                [        ]],["AbstractGetMappingRequest","Elastification\/Client\/Request\/Shared\/AbstractGetMappingRequest.html"," < AbstractBaseRequest",
                [        ]],["AbstractSearchRequest","Elastification\/Client\/Request\/Shared\/AbstractSearchRequest.html"," < AbstractBaseRequest",
                [        ]],["AbstractUpdateDocumentRequest","Elastification\/Client\/Request\/Shared\/AbstractUpdateDocumentRequest.html"," < AbstractBaseRequest",
                [        ]]        ]],["V090x","Elastification\/Client\/Request\/V090x.html","",
                [["CreateDocumentRequest","Elastification\/Client\/Request\/V090x\/CreateDocumentRequest.html"," < AbstractCreateDocumentRequest",
                [        ]],["DeleteDocumentRequest","Elastification\/Client\/Request\/V090x\/DeleteDocumentRequest.html"," < AbstractDeleteDocumentRequest",
                [        ]],["GetDocumentRequest","Elastification\/Client\/Request\/V090x\/GetDocumentRequest.html"," < AbstractGetDocumentRequest",
                [        ]],["GetMappingRequest","Elastification\/Client\/Request\/V090x\/GetMappingRequest.html"," < AbstractGetMappingRequest",
                [        ]],["SearchRequest","Elastification\/Client\/Request\/V090x\/SearchRequest.html"," < AbstractSearchRequest",
                [        ]],["UpdateDocumentRequest","Elastification\/Client\/Request\/V090x\/UpdateDocumentRequest.html"," < AbstractUpdateDocumentRequest",
                [        ]]        ]],["V1x","Elastification\/Client\/Request\/V1x.html","",
                [["CreateDocumentRequest","Elastification\/Client\/Request\/V1x\/CreateDocumentRequest.html"," < AbstractCreateDocumentRequest",
                [        ]],["DeleteDocumentRequest","Elastification\/Client\/Request\/V1x\/DeleteDocumentRequest.html"," < AbstractDeleteDocumentRequest",
                [        ]],["GetDocumentRequest","Elastification\/Client\/Request\/V1x\/GetDocumentRequest.html"," < AbstractGetDocumentRequest",
                [        ]],["SearchRequest","Elastification\/Client\/Request\/V1x\/SearchRequest.html"," < AbstractSearchRequest",
                [        ]],["UpdateDocumentRequest","Elastification\/Client\/Request\/V1x\/UpdateDocumentRequest.html"," < AbstractUpdateDocumentRequest",
                [        ]]        ]],["RequestInterface","Elastification\/Client\/Request\/RequestInterface.html","",
                [        ]],["RequestManager","Elastification\/Client\/Request\/RequestManager.html","",
                [        ]],["RequestManagerInterface","Elastification\/Client\/Request\/RequestManagerInterface.html","",
                [        ]],["RequestMethods","Elastification\/Client\/Request\/RequestMethods.html","",
                [        ]]        ]],["Response","Elastification\/Client\/Response.html","",
                [["Shared","Elastification\/Client\/Response\/Shared.html","",
                [["AbstractSearchResponse","Elastification\/Client\/Response\/Shared\/AbstractSearchResponse.html"," < Response",
                [        ]]        ]],["V090x","Elastification\/Client\/Response\/V090x.html","",
                [["CreateUpdateDocumentResponse","Elastification\/Client\/Response\/V090x\/CreateUpdateDocumentResponse.html"," < Response",
                [        ]],["DeleteDocumentResponse","Elastification\/Client\/Response\/V090x\/DeleteDocumentResponse.html"," < Response",
                [        ]],["DocumentResponse","Elastification\/Client\/Response\/V090x\/DocumentResponse.html"," < Response",
                [        ]],["SearchResponse","Elastification\/Client\/Response\/V090x\/SearchResponse.html"," < AbstractSearchResponse",
                [        ]]        ]],["V1x","Elastification\/Client\/Response\/V1x.html","",
                [["CreateUpdateDocumentResponse","Elastification\/Client\/Response\/V1x\/CreateUpdateDocumentResponse.html"," < Response",
                [        ]],["DeleteDocumentResponse","Elastification\/Client\/Response\/V1x\/DeleteDocumentResponse.html"," < Response",
                [        ]],["DocumentResponse","Elastification\/Client\/Response\/V1x\/DocumentResponse.html"," < Response",
                [        ]],["SearchResponse","Elastification\/Client\/Response\/V1x\/SearchResponse.html"," < AbstractSearchResponse",
                [        ]]        ]],["Response","Elastification\/Client\/Response\/Response.html","",
                [        ]],["ResponseInterface","Elastification\/Client\/Response\/ResponseInterface.html","",
                [        ]]        ]],["Serializer","Elastification\/Client\/Serializer.html","",
                [["Exception","Elastification\/Client\/Serializer\/Exception.html","",
                [["DeserializationFailureException","Elastification\/Client\/Serializer\/Exception\/DeserializationFailureException.html"," < RuntimeException",
                [        ]]        ]],["Gateway","Elastification\/Client\/Serializer\/Gateway.html","",
                [["GatewayInterface","Elastification\/Client\/Serializer\/Gateway\/GatewayInterface.html","",
                [        ]],["NativeArrayGateway","Elastification\/Client\/Serializer\/Gateway\/NativeArrayGateway.html","",
                [        ]],["NativeObjectGateway","Elastification\/Client\/Serializer\/Gateway\/NativeObjectGateway.html","",
                [        ]]        ]],["JmsSerializer","Elastification\/Client\/Serializer\/JmsSerializer.html","",
                [["Hit","Elastification\/Client\/Serializer\/JmsSerializer\/Hit.html","",
                [        ]],["Hits","Elastification\/Client\/Serializer\/JmsSerializer\/Hits.html","",
                [        ]],["SearchResponseEntity","Elastification\/Client\/Serializer\/JmsSerializer\/SearchResponseEntity.html","",
                [        ]],["Shards","Elastification\/Client\/Serializer\/JmsSerializer\/Shards.html","",
                [        ]],["SourceSubscribingHandler","Elastification\/Client\/Serializer\/JmsSerializer\/SourceSubscribingHandler.html","",
                [        ]]        ]],["DoNothingSerializer","Elastification\/Client\/Serializer\/DoNothingSerializer.html","",
                [        ]],["JmsSerializer","Elastification\/Client\/Serializer\/JmsSerializer.html","",
                [        ]],["NativeJsonSerializer","Elastification\/Client\/Serializer\/NativeJsonSerializer.html","",
                [        ]],["SerializerInterface","Elastification\/Client\/Serializer\/SerializerInterface.html","",
                [        ]]        ]],["Transport","Elastification\/Client\/Transport.html","",
                [["Exception","Elastification\/Client\/Transport\/Exception.html","",
                [["TransportLayerException","Elastification\/Client\/Transport\/Exception\/TransportLayerException.html"," < RuntimeException",
                [        ]]        ]],["HttpGuzzle","Elastification\/Client\/Transport\/HttpGuzzle.html","",
                [["GuzzleTransport","Elastification\/Client\/Transport\/HttpGuzzle\/GuzzleTransport.html","",
                [        ]],["GuzzleTransportRequest","Elastification\/Client\/Transport\/HttpGuzzle\/GuzzleTransportRequest.html","",
                [        ]],["GuzzleTransportResponse","Elastification\/Client\/Transport\/HttpGuzzle\/GuzzleTransportResponse.html","",
                [        ]]        ]],["Thrift","Elastification\/Client\/Transport\/Thrift.html","",
                [["ThriftConnectionFactory","Elastification\/Client\/Transport\/Thrift\/ThriftConnectionFactory.html","",
                [        ]],["ThriftRequest","Elastification\/Client\/Transport\/Thrift\/ThriftRequest.html","",
                [        ]],["ThriftResponse","Elastification\/Client\/Transport\/Thrift\/ThriftResponse.html","",
                [        ]],["ThriftTransport","Elastification\/Client\/Transport\/Thrift\/ThriftTransport.html","",
                [        ]]        ]],["TransportInterface","Elastification\/Client\/Transport\/TransportInterface.html","",
                [        ]],["TransportRequestInterface","Elastification\/Client\/Transport\/TransportRequestInterface.html","",
                [        ]],["TransportResponseInterface","Elastification\/Client\/Transport\/TransportResponseInterface.html","",
                [        ]]        ]],["Client","Elastification\/Client\/Client.html","",
                [        ]],["ClientInterface","Elastification\/Client\/ClientInterface.html","",
                [        ]],["ClientVersionMap","Elastification\/Client\/ClientVersionMap.html","",
                [        ]]        ]]        ]]        ]

